### ISSUE TITLE
web server should be decoupled from logging and should be run explicitly

### ISSUE THREAD

**Issue by restyler** [errsole/errsole.js#87]
I am a bit confused but it looks like errsole is not designed to be used via several processes.
let's say I have `server.js` with my express.js server which sends some logs and I also have `script1.js` which is a cron job I run from time to time which I want to enable to send logs into errsole as well.
Apparently it's not possible to have this setup right now (or at least, it is not clear how to implement this in docs).

```js
import errsole from 'errsole';
import ErrsoleSQLite from 'errsole-sqlite';


// THIS LINE SHOULD NOT RUN THE WEB SERVER IMPLICITLY
errsole.initialize({
    storage: new ErrsoleSQLite('logs2.db')
});

```

this is the error I am getting.
```
Error: listen EADDRINUSE: address already in use :::8001
    at Server.setupListenHandle [as _listen2] (node:net:1485:16)
    at listenInCluster (node:net:1533:12)
    at Server.listen (node:net:1621:7)
    at Function.listen (/Users/anton/dev/scrapeninja-claude-tools/node_modules/express/lib/application.js:635:24)
    at Object.startServer (/Users/anton/dev/scrapeninja-claude-tools/node_modules/errsole/lib/main/index.js:43:18)
    at Object.initialize (/Users/anton/dev/scrapeninja-claude-tools/node_modules/errsole/lib/main/index.js:17:10)
    at Errsole.initialize (/Users/anton/dev/scrapeninja-claude-tools/node_modules/errsole/lib/errsole.js:18:15)
    at file:///Users/anton/dev/scrapeninja-claude-tools/src/test-errsole-logs.js:7:9
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
```

**Comment by mrrishimeena** [comment]
Can you configure, 'enableDashboard' to false in cron-job and try.

Doc: https://github.com/errsole/errsole.js/blob/master/docs/sqlite-storage.md#advanced-configuration

**Comment by restyler** [comment]
thanks, this helped!
